package logger;

/**
 * @brief Enum for internal log messages.
 */
public enum TokenInternalLogMessage {
    CLIENT_LOG_SOCKET_OPEN(),
    CLIENT_LOG_SOCKET_CLOSED(),
    CLIENT_LOG_SIGN_UP_OK(),
    CLIENT_LOG_SIGN_UP_KO(),
    CLIENT_LOG_SIGN_IN_KO(),
    SERVER_LOG_CLIENT_HANDLER_CREATED(),
    CLIENT_LOG_SIGN_IN_OK(),
    CLIENT_LOG_DOMAIN_LIST_OK(),
    CLIENT_LOG_DOMAIN_LIST_KO(),
    CLIENT_LOG_UNREACHABLE_SERVER(),
    CLIENT_LOG_SIGN_OUT_OK(),
    CLIENT_LOG_SIGN_OUT_KO(),
    SERVER_LOG_CLIENT_CREATED(),
    SERVER_LOG_CLIENT_HANDLER(),
    CLIENT_LOG_SALE_CREATED_OK(),
    CLIENT_LOG_SALE_CREATED_KO(),
    SERVER_LOG_CREATE_SALE(),
    CLIENT_LOG_SALE_UPDATED_OK(),
    CLIENT_LOG_SALE_UPDATED_KO(),
    SERVER_LOG_UPDATE_SALE(),
    CLIENT_LOG_SALES_FROM_DOMAIN_OK(),
    CLIENT_LOG_DELETE_SALE_OK(),
    CLIENT_LOG_DELETE_SALE_KO(),
    CLIENT_LOG_SALES_FROM_DOMAIN_KO,
    SERVER_LOG_DELETE_SALE(),
    CLIENT_LOG_REQUEST_PUBLIC_KEY_OK(),
    CLIENT_LOG_REQUEST_PUBLIC_KEY_KO(),
    CLIENT_LOG_UDP_SERVER_OK(),
    CLIENT_LOG_UDP_SERVER_KO(), 
}