sequenceDiagram
participant Client
participant ClientHandler
Client->>ClientHandler: SALE_FROM_DOMAIN (domain)
alt success
    ClientHandler->>Client: SALE_FROM_DOMAIN_OK (sales)
else failure
    ClientHandler->>Client: SALE_FRON_DOMAIN_KO (message)
end